### ISSUE TITLE
Panic in resourceDigitalOceanAppRead

### ISSUE THREAD

**Issue by nightvisi0n** [digitalocean/terraform-provider-digitalocean#678]
# Bug Report

Today I tried to apply my terraform config, which ended in the following error:

```
Stack trace from the terraform-provider-digitalocean_v2.11.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdfe531]

goroutine 72 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanAppRead(0x123ae98, 0xc0000ad620, 0xc00052a000, 0xf60860, 0xc0005af740, 0xc000437920, 0xc00062b908, 0x40e0f8)
        github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_app.go:111 +0x471
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001888c0, 0x123ae28, 0xc0003c7700, 0xc00052a000, 0xf60860, 0xc0005af740, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001888c0, 0x123ae28, 0xc0003c7700, 0xc0003ac7e0, 0xf60860, 0xc0005af740, 0xc0004967a0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000b0090, 0x123ae28, 0xc0003c7700, 0xc0003c7740, 0xc0003c7700, 0x40b965, 0x1007960)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0000ba380, 0x123aed0, 0xc0003c7700, 0xc0008923c0, 0xc0000ba380, 0xc000739620, 0xc000815ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1049820, 0xc0000ba380, 0x123aed0, 0xc000739620, 0xc000892360, 0x0, 0x123aed0, 0xc000739620, 0xc00042ec00, 0x1065)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d6540, 0x1244738, 0xc000642f00, 0xc000820000, 0xc0005ae120, 0x17d8b90, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000d6540, 0x1244738, 0xc000642f00, 0xc000820000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b61c0, 0xc0000d6540, 0x1244738, 0xc000642f00, 0xc000820000)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-digitalocean_v2.11.1 plugin crashed!
```

It seems this bug occurs in any operation where the current state from the DO App Platform has to be read.

The terraform config uses the following resources:
- digitalocean_database_cluster
- digitalocean_database_db
- digitalocean_database_user
- digitalocean_app

If you need any more info please let me know.

**Comment by danaelhe** [comment]
Hi there,

Would it be possible to include your terraform config file? Has this config file always been erroring out or has it ever been successful?

Thanks!

**Comment by nightvisi0n** [comment]
Hi, after further investigation it seems like this only happens if the initial deployment fails (e.g. due to a missing image in DOCR).  
The same config worked after a manual (successful) deployment.  
I think this bug is reproducible by deploying a minimal app with a non-existent DOCR image (which will fail).
