### ISSUE TITLE
Terraform floating IP assignment import leads to crash

### ISSUE THREAD

**Issue by SamWhited** [digitalocean/terraform-provider-digitalocean#763]
# Bug Report

While trying to do an import of a digitalocean_floating_ip_assignment (that somehow didn't get updated in the state after the `terraform apply` that created the assignment, which might be another bug but I don't have any information or any indication of why this happened), Terraform crashed. The import was likely incorrect, but the docs don't mention what information is needed so I tried this.

```
$ terraform import module.prod.digitalocean_floating_ip_assignment.gitea "167.99.22.167"
module.prod.digitalocean_floating_ip_assignment.gitea: Importing from ID "167.99.22.167"...
module.prod.digitalocean_floating_ip_assignment.gitea: Import prepared!
  Prepared digitalocean_floating_ip_assignment for import
module.prod.digitalocean_floating_ip_assignment.gitea: Refreshing state... [id=167.99.22.167]
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵


Stack trace from the terraform-provider-digitalocean_v2.16.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe359ab]

goroutine 38 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanFloatingIpAssignmentRead(0x1247538, 0xc0004a68a0, 0xc0005e4b80, 0xf6ab40, 0xc00056bc80, 0xc000694280, 0xc000693908, 0x40e0f8)
        github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_floating_ip_assignment.go:77 +0x2ab
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0002f0700, 0x12474c8, 0xc000053fc0, 0xc0005e4b80, 0xf6ab40, 0xc00056bc80, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002f0700, 0x12474c8, 0xc000053fc0, 0xc0004b84d0, 0xf6ab40, 0xc00056bc80, 0xc00069c1f0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c048, 0x12474c8, 0xc000053fc0, 0xc0004be000, 0xc000053fc0, 0x40b965, 0x1011ee0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0005a8f60, 0x1247570, 0xc000053fc0, 0xc0004a6480, 0xc0005a8f60, 0xc0004ba300, 0xc0004b2ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1053dc0, 0xc0005a8f60, 0x1247570, 0xc0004ba300, 0xc0004a6420, 0x0, 0x1247570, 0xc0004ba300, 0xc000048230, 0x70)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00034e000, 0x1250d18, 0xc00048af00, 0xc000170d00, 0xc0003c4450, 0x17e8bf0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00034e000, 0x1250d18, 0xc00048af00, 0xc000170d00, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00049c160, 0xc00034e000, 0x1250d18, 0xc00048af00, 0xc000170d00)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-digitalocean_v2.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Affected Resource(s)

- digitalocean_floating_ip_assignment

**Terraform Configuration Files**

I am unsure what parts are helpful and can't create a MWE, so here is the upstream repo with all the files: https://codeberg.org/codeforge.coop/codeforge-ops/src/branch/main/deploy

```
$ terraform -v
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.16.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

**Debug Output**

https://gist.github.com/SamWhited/1b719664a6246aeb987fd0ca85690542

**Panic Output**

No `crash.log` file anywhere that I could find (`find / -name 'crash.log' 2>/dev/null`).

**Comment by danaelhe** [comment]
Thank you for the write up! We will look into it as soon as we can.

**Comment by andrewsomething** [comment]
Hi @SamWhited,

Unfortunately, it looks like support for importing existing floating IP assignments was never properly implemented. That's likely why the docs do not mention it. I've added support in https://github.com/digitalocean/terraform-provider-digitalocean/pull/771 Once that lands, the way to import one will be to use the Floating IP itself and the `id` of the Droplet joined with a comma. For example:

    terraform import digitalocean_floating_ip_assignment.foobar 192.0.2.1,123456
